name: datan_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pandas
  - matplotlib
  - tqdm
  - jupyter
  - numpy
  - lxml
  - openpyxl
  - geopandas
  - cartopy
  - html5lib
  - streamlit-aggrid
